services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web
    depends_on:
      - postgres
    command: pnpm run dev
  
  worker-attachments:
    container_name: worker-attachments
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web
    depends_on:
      - redis
    command: pnpm run worker:attachments

  worker-messages:
    container_name: worker-messages
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web
    depends_on:
      - redis
    command: pnpm run worker:messages 

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - web

volumes:
  postgres_data:
  redisdata:

networks:
  web:
    driver: bridge